import type { TCRSDataResponse } from '../../../types';

export function createEmptyResponse(className: string, moonSign: string): TCRSDataResponse {
  return {
    className,
    moonSign,
    allItems: [],
    turnGeneration: {
      food: [],
      booze: [],
      rolloverAdventures: [],
      odeToBooze: [],
      garish: [],
    },
    generalQuestBuffs: {
      noncombat: [],
      combat: [],
      monsterLevel: [],
      normalItemDrop: [],
      foodDrop: [],
      boozeDrop: [],
      meatDrop: [],
      statGainsBasic: [],
      statGainsMus: [],
      statGainsMys: [],
      statGainsMox: [],
      familiarWeight: [],
      familiarExp: [],
      initiative: [],
    },
    questSpecificBuffs: {
      minusMonsterLevel: [],
      frostyEffect: [],
      flatWeaponDamage: [],
      weaponDamagePercent: [],
      flatSpellDamage: [],
      spellDamagePercent: [],
      resCold: [],
      resHot: [],
      resStench: [],
      resSpooky: [],
      resSleaze: [],
      dmgCold: [],
      dmgHot: [],
      dmgStench: [],
      dmgSpooky: [],
      dmgSleaze: [],
    },
    survivalBuffs: {
      superSkill: [],
      odeToBooze: [],
      frosty: [],
      inigos: [],
      flatMuscle: [],
      musclePercent: [],
      flatMysticality: [],
      mysticalityPercent: [],
      flatMoxie: [],
      moxiePercent: [],
      damageAbsorption: [],
      mpRegen: [],
    },
    summary: {},
  };
}
