export const zoneCategories: Record<string, string> = {
  'the haunted pantry': 'Early Spookyraven',
  'the haunted kitchen': 'Early Spookyraven',
  'the haunted library': 'Early Spookyraven',
  'the haunted billiards room': 'Early Spookyraven',
  'the haunted gallery': 'Early Spookyraven',
  'the haunted bathroom': 'Early Spookyraven',
  'the haunted bedroom': 'Early Spookyraven',
  'the haunted ballroom': 'Early Spookyraven',
  "vanya's castle": '8-Bit Realm',
  'megalo-city': '8-Bit Realm',
  "hero's field": '8-Bit Realm',
  'the fungus plains': '8-Bit Realm',
  'the spooky forest': 'L3: Typical Tavern',
  'the typical tavern cellar': 'L3: Typical Tavern',
  'the bat hole entrance': 'L4: Bat Hole',
  'guano junction': 'L4: Bat Hole',
  'the batrat and ratbat burrow': 'L4: Bat Hole',
  'the beanbat chamber': 'L4: Bat Hole',
  "the boss bat's lair": 'L4: Bat Hole',
  "the outskirts of cobb's knob": "L5: Cobb's Knob",
  "cobb's knob harem": "L5: Cobb's Knob",
  'throne room': "L5: Cobb's Knob",
  'the dark neck of the woods': 'L6: Deep Fat Friars / Steel Organ',
  'the dark heart of the woods': 'L6: Deep Fat Friars / Steel Organ',
  'the dark elbow of the woods': 'L6: Deep Fat Friars / Steel Organ',
  'the laugh floor': 'L6: Deep Fat Friars / Steel Organ',
  'infernal rackets backstage': 'L6: Deep Fat Friars / Steel Organ',
  'the defiled nook': 'L7: Defiled Cyrpt',
  'the defiled niche': 'L7: Defiled Cyrpt',
  'the defiled cranny': 'L7: Defiled Cyrpt',
  'the defiled alcove': 'L7: Defiled Cyrpt',
  'itznotyerzitz mine': 'L8: McLargeHuge',
  'the goatlet': 'L8: McLargeHuge',
  'the extreme slope': 'L8: McLargeHuge',
  'lair of the ninja snowmen': 'L8: McLargeHuge',
  'the icy peak': 'L8: McLargeHuge',
  'the smut orc logging camp': 'L9: Orc Chasm',
  "the valley of rof l'm fao": 'L9: Orc Chasm',
  'a-boo peak': 'L9: Orc Chasm',
  'twin peak': 'L9: Orc Chasm',
  'oil peak': 'L9: Orc Chasm',
  'the castle in the clouds in the sky (basement)': "L10: Giant's Trash",
  'the castle in the clouds in the sky (ground floor)': "L10: Giant's Trash",
  'the castle in the clouds in the sky (top floor)': "L10: Giant's Trash",
  'the penultimate fantasy airship': "L10: Giant's Trash",
  'the hole in the sky': "L10: Giant's Trash",
  'the black forest': 'L11: Holy MacGuffin',
  'the hidden temple': 'L11: Holy MacGuffin',
  'the hidden apartment building': 'L11: Holy MacGuffin',
  'the hidden hospital': 'L11: Holy MacGuffin',
  'the hidden office building': 'L11: Holy MacGuffin',
  'the hidden bowling alley': 'L11: Holy MacGuffin',
  'a mob of zeppelin protesters': 'L11: Holy MacGuffin',
  'the red zeppelin': 'L11: Holy MacGuffin',
  'the arid, extra-dry desert': 'L11: Holy MacGuffin',
  'an oasis': 'L11: Holy MacGuffin',
  'the upper chamber': 'L11: Holy MacGuffin',
  'the middle chamber': 'L11: Holy MacGuffin',
  'the lower chambers': 'L11: Holy MacGuffin',
  'a maze of sewer tunnels': 'L11: Holy MacGuffin',
  'the spookyraven manor wine cellar': 'L11: Holy MacGuffin',
  'the spookyraven manor laundry room': 'L11: Holy MacGuffin',
  'the spookyraven manor boiler room': 'L11: Holy MacGuffin',
  'cobbs knob laboratory': 'L11: Holy MacGuffin',
  "cobb's knob menagerie, level 1": 'L11: Holy MacGuffin',
  "cobb's knob menagerie, level 2": 'L11: Holy MacGuffin',
  "cobb's knob menagerie, level 3": 'L11: Holy MacGuffin',
  'the copperhead club': 'L11: Holy MacGuffin',
  'shen shenanigans': 'L11: Holy MacGuffin',
  'inside the palindome': 'L11: Holy MacGuffin',
  "whitey's grove": 'L11: Holy MacGuffin',
  'the hidden park': 'L11: Holy MacGuffin',
  'the battlefield (frat uniform)': 'L12: Island War',
  'the battlefield (hippy uniform)': 'L12: Island War',
  'hippy camp': 'L12: Island War',
  'the hippy camp (bombed back to the stone age)': 'L12: Island War',
  'frat house': 'L12: Island War',
  'the frat house (bombed back to the stone age)': 'L12: Island War',
  'wartime hippy camp': 'L12: Island War',
  'wartime frat house': 'L12: Island War',
  'the junkyard': 'L12: Island War',
  "mctwoboss's junkyard": 'L12: Island War',
  'sonofa beach': 'L12: Island War',
  'the arena': 'L12: Island War',
  'the organic produce stand': 'L12: Island War',
  'the themthar hills': 'L12: Island War',
  'the hatching chamber': 'L12: Island War',
  'the feeding chamber': 'L12: Island War',
  "the guards' chamber": 'L12: Island War',
  "the queen's chamber": 'L12: Island War',
  'the slime tube': 'Misc IOTM',
  dreadsylvania: 'Misc IOTM',
  'hobopolis town square': 'Misc IOTM',
  'burnbarrel blvd.': 'Misc IOTM',
  'exposure lodge': 'Misc IOTM',
  'the heap': 'Misc IOTM',
  'the ancient hobo burial ground': 'Misc IOTM',
  'purple light district': 'Misc IOTM',
  'fast food restaurant': 'Misc IOTM',
  'the f-o-m-a-r-t': 'Misc IOTM',
  'the glaciest': 'Misc IOTM',
  'the deep dark jungle': 'Misc IOTM',
  'the secret government laboratory': 'Misc IOTM',
  'the neverending party': 'Misc IOTM',
  snojo: 'Misc IOTM',
  'barf mountain': 'Misc IOTM',
  "the pirate's cove": 'Misc Maybe Useful?',
  'the obliviscoratu': 'Misc Maybe Useful?',
  'the defiled cranny boss': 'Misc Maybe Useful?',
  'the daily dungeon': 'Misc Maybe Useful?',
  'dungeons of doom': 'Misc Maybe Useful?',
  'the obelisk': 'Misc Maybe Useful?',
  'the dire warren': 'Misc Maybe Useful?',
  'noob cave': 'Misc Maybe Useful?',
  '8-bit realm': 'Misc Maybe Useful?',
  'shadow rifts': 'Misc Maybe Useful?',
};

export function categorizeZone(location: string): string {
  const locLower = location.toLowerCase();

  // Direct lookup first
  if (zoneCategories[locLower]) {
    return zoneCategories[locLower];
  }

  // Fallback for partial matches (e.g. if the zone has a suffix like (Hippy))
  for (const [key, value] of Object.entries(zoneCategories)) {
    if (locLower.includes(key) || key.includes(locLower)) {
      return value;
    }
  }

  return 'Other / Miscellaneous';
}
